
#   _____   _               _       _____
#  / ____| | |             | |     |  __ \
# | |      | |__     __ _  | |_    | |__) |  _ __    ___
# | |      | '_ \   / _` | | __|   |  ___/  | '__|  / _ \
# | |____  | | | | | (_| | | |_    | |      | |    | (_) |
#  \_____| |_| |_|  \__,_|  \__|   |_|      |_|     \___/

update-checker:
  enabled: true

  # When an update is found, should it be printed to the console?
  print-to-console: true

  # When an update is found, should players with the permission "ChatPro.Notify" be notified?
  notify-in-game: true

colours:
  # Enable colorCodes in player messages
  enabled: true

  # Allow you to set any default chat color that can be chosen in the /color command.
  default-chat-color: "default"

  # The message that gets sent if the player doesn't have permission to execute the command
  # Note: ColorCodes are supported in the message.
  color-command-no-permission: "You do not have permission to execute this command."

format:
  # Changes the format of a player message: "Player:" instead of "<Player>".
  better-message-format: true

censoring:
  # Allow the player to choose if they want to censor their messages, instead of it being filtered server side.
  client-side-filtering: true;

  # List of stings that will be filtered by the plugin.
  filtered-words: ['Fuck', 'Shit', 'ChatPro is bad']
  filter-ip: true

  # Blocks any message that contains a filtered word.
  block-message: false
  blocked-message-notification: "Your message contained a filtered word, and it has been canceled."

  # Replace the filtered word instead of blocking the entire message.
  replace-word-in-message: true
  filtered-word-replacement: "*"



